# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios
  pod 'client', :path => '../common/client'

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'clientTest', :path => '../common/client'
  end

  target 'iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
